---
title: "Parallel Sessions 1"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br></br>  

### **4th August, 2021**  
### **11:00 - 12:40 (MY time)**  

Select a room and session below to reveal more details and to access the button to join.  

***  

## {.tabset}  

### **ROOM 1 - MERBOK ROOM**  

> #### **iCMS2021: 003-001 - A review on individual loss reserving for non-life insurance**  
> Presented by: **_Ang Siew Ling_**  
> Start Time: **_11:00 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*In recent decades, there has been great success with deterministic and stochastic unpaid claim reserving models based on triangles, such as those related to the chain-ladder model. However, with the increased need for more accurate reserving models, taking advantage of the information embedded in individual claims data with appropriate claims development models are a promising alternative compared with the traditional aggregate loss development triangles. This research reviews on the development of using the individual claims data for reserving estimation.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 019-017 - Statistical analysis on the effectiveness of short-term program during Covid-19 pandemic : In the case of Program Bijak Sifir 2020**  
> Presented by: **_Nazihah binti Safie_**  
> Start Time: **_11:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*At the start of 2020, the whole world faced the covid-19 pandemic spreading across countries, including Malaysia. The pandemic caused the Malaysia government to take immediate  action to declare a Movement Control order (MCO). This MCO has a serious impact on almost all Malay-sia sectors, including the economic, social, and education sectors. For primary school students to strengthen their mathematics skills, we believed that short programs significantly affect their   performance during MCO implementation. This study was conducted to measure the primary school students' performance during MCO for the short term Mathematics program. There were two sets of mathematics score data before and after the program considered in this study. The Mann-Whitney test was conducted to test whether there is any significant difference in perfor-mance between genders for both data sets. Meanwhile, the Wilcoxon Signed Rank test was conducted to evaluate student performance's significant difference before and after the program. It was found that there was a significant difference in students' performance before and after the program, which the performance after the program becomes increased. One of the possible factors that were given a   significant effect on the student's performance was program activities' effectiveness using face-to-face platforms. However, it only carried out in a short term pe-riod. As we believed, face-to-face teaching and learning activities are still necessary for all education levels, especially at the primary level, even if it only involves a short period. Nonethe-less, the hybrid platform of    teaching and learning must be prepared due to the pandemic era's uncertainty.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 068-056 - A Semi Analytical Iterative Method for Solving Emden-Fowler Equations**  
> Presented by: **_Mohd Najir Tokachil_**  
> Start Time: **_11:30 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*In this paper, some exact solutions of Emden-Fowler equations have been obtained by imple-mented a semi analytical iterative method (SAIM). Transformation approached is applied to overcome the difficulties of singularity behavior that occurs in Emden-Fowler equation. The re-sults demonstrates that the SAIM is very effective and reliable and does not require any restric-tive assumption for nonlinear terms.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 015-008 - Depression Detection based on Twitter using NLP and Sentiment Analysis**  
> Presented by: **_Yam Zheng Lim_**  
> Start Time: **_11:45 (MY time)_**  
> 
> Track - Computer Science   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Depression is a most common illness and serious disease where some people cannot detect it by themselves. Depression is underestimated by human beings, sometimes human even not realize that they are struggling in depression. A serious depression will affect the emotion, physical condition, or even cause someone suicide. One of the ways to detect depression is by reading through their social media post. Social media is widely used in this 21th century. Users will normally post for communicate and express their emotion. This research aims to develop a sys-tem that used to analyze the user depress status base on their social media post. The system will scrape the user social media post, and analyze the depress status about the user. The research will implement RNN model and CNN model in order to get the most accuracy parameter for building the model and compare the accuracy of the prediction towards this depression issues. The end results output of the system is to give user’s depression status. Through this system, the system will notify the user about their depress status. If they having depression problem, they might or suggested to ask treatment with phycologist. By informing users depress status, user might have the awareness of their mental problem.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 090-074 - Maximum Likelihood Estimation of Replicated Linear Functional Relationship Model**  
> Presented by: **_Azuraini Mohd Arif_**  
> Start Time: **_12:00 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*This paper discusses the parameter estimates as well as the asymptotic covariance in replicated LFRM. The model is assumed to be balanced and equal in each group. All the parameters can be estimated using the maximum likelihood estimation method. Although the closed-form of the estimates is not available, it is shown that the closed-form for the asymptotic covariance matrix of the model using the Fisher Information matrix can be obtained. Using results from the simu-lation study, we showed that the estimated values of the parameters are unbiased and consistent.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 089-071 - Modeling The Effectiveness Of Teaching Basic Numbers Through Mini Tennis Training  Using**  
> Presented by: **_Rahela Abdul Rahim_**  
> Start Time: **_12:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Mathematics is often considered a difficult and boring subject for most children because its use in daily activities is not given proper emphasis. The activity of counting numbers in ascending order is the basis of learning mathematics. While the activity of playing through physical movement is the most popular activity by children. Therefore, an approach should be taken to build a relationship between mathematics learning and physical activity games so that children can gain skills in both areas in parallel and can save time, energy and human resource costs. This study pioneered the technique of learning to make basic number calculations for children through a tennis mini game called AB-kiRA. To measure the effectiveness of this technique a Markov chain model was developed to analyze the performance of trainees in making basic number calculations during mini tennis training. Data from 150 training trials were used to generate the transition matrix. Next a calculation to obtain the probability of the equilibrium state is performed. The results show that the trainees will be able to master the basic number counting skills after 10 attempts are made through the shot of the ball made by the trainee. This information can be the basis of a guide for training other mini tennis trainee children in mastering basic number counting skills.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 063-051 - Some Robust Ridge Regression Approach for the Combined Multi-collinearity-Outlier Problem**  
> Presented by: **_Sanizah Ahmad_**  
> Start Time: **_12:30 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The common method used for estimating parameters in linear regression model is ordinary least squares (OLS) since it gives the best parameter estimates when all assumptions are met. In reality, these assumptions are sometimes not adhered since the presence of combined multicollinearity and outliers often occur in regression data. When this is the case, analysing regression model may severe-ly produce misleading results. To overcome this issue, various robust parameter estimates were in-jected into ridge regression method to produce robust ridge regression models. Therefore, the aim of this study is to investigate on the performance of selected robust ridge estimators which include S, M, MM and Least Trimmed Squares (LTS) estimators using simulation study. For the simulation de-sign, Laplace and Cauchy distributions were used to introduce outliers in the simulated data of sample sizes n=25, 50 and 100 with various level of multicollinearity ($\rho$ = 0.50, 0.90, 0.95, 0.98, 0.99). Root Mean Square Error and Bias are used as the criterion measure to examine the performance for the estimators. The finding of this study indicates that Ridge LTS is the best robust ridge estimator in handling data containing both multicollinearity and outliers. Applications of the estimators to two benchmark real life datasets provide similar results.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

***  

### **ROOM 2 - JERAI ROOM**  

> #### **iCMS2021: 050-040 - Assessing the Relations of Students' Learning Styles and Critical Thinking in Mathematics in a 'Cluster School'**  
> Presented by: **_Asyura Abd Nassir_**  
> Start Time: **_11:00 (MY time)_**  
> 
> Track - Computer Science/ Mathematics/ Statistics Education (CMS)   

<details>
<summary>**_Abstract_**</summary>  
<p>
*All individuals have a different dimension of learning, such as visual learners, auditory learners, and kinesthetic learners. Identifying students' learning styles in class can help teachers plan a strategy for adapting the best teaching method to help them understand. This study aims to identify the potential relationship between the students' preferred learning style and their critical thinking in Mathematics. This study sample involves students at a 'cluster' secondary school in Pahang, Malaysia. A set of questionnaires consists of fourteen questions and critical thinking problems distributed to sixty-two 17-year-old students. The quantitative data collected were ana-lyzed using descriptive statistics, Spearman's Rank Correlation Coefficient, and ANOVA and t-test. The results indicate that the most popular learning style is visual, followed by auditory and kinaesthetic. The most preferred learning style for students in this study is visual, giving 71 per-cent of them are visual learners. For the auditory and kinaesthetic learners, it provides only 22.6 and 6.5 percent, respectively. It also shows that the preferred learning style and critical thinking are not significantly related. This study suggests that teachers should make some efforts to pro-vide various teaching methods consistent with the students' learning style. In contrast, students need to adjust their learning styles to match the teachers' teaching methods. Furthermore, it will help the students to build self-confidence and plan their study strategy.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 033-023 - Radiative Casson Fluid over a Slippery Vertical Riga Plate with Viscous Dissipation**  
> Presented by: **_Khadijah Abdul Hamid_**  
> Start Time: **_11:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The application of Casson fluid such as concentrated fruit juice and tomato sauce might involve problem during the manufacturing process to maintain their high quality.  This study aims to investigate the radiative Casson fluid in the presence of magnetic field, velocity slip, thermal slip, viscous dissipation and buoyancy effects over a permeable slippery vertical Riga stretching and shrinking plates. The governing partial differential equations are translated into ordinary dif-ferential equations using similarity transformation.  The equations are then solved numerically using a boundary value problem solver (BVP4C) in MATLAB software.  The Casson fluid and the modified Hartmann number influence to increase the skin friction coefficient and the heat transfer rate for both stretching and shrinking surfaces.  These two factors increase the fluid flow but decrease the heat distributions. This theoretical research becomes a benchmark for the exper-imental research in the study of the Casson fluid.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 085-072 - Performance of Mortality Rates Using Deep Learning Approach**  
> Presented by: **_Saiful Izzuan Hussain_**  
> Start Time: **_11:30 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Mortality has a vital role in population dynamics and is critical in a wide variety of fields, includ-ing demography, economics, and social sciences. This study aims to model and compare the mortality rate using two different models; the Lee-Carter model and Deep Neural Network (DNN). The sample data used is the case of the United Kingdom population. Mortality rates were modeled with the Lee-Carter model and deviance goodness of fit were used to test the model's suitability of the data. Next, mortality rates are modeled with the Deep Neural Network (DNN) and both models are compared based on the mean square error (MSE) values. The results showed that the DNN model fits the best. Overall, we conclude that DNN approach appears to be a potential model to model and forecast population mortality.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 087-069 - Dynamics simulation approach in development of unsold new residential housing in Johor**  
> Presented by: **_Lok Lee Wen_**  
> Start Time: **_11:45 (MY time)_**  
> 
> Track - Computer Science   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The unsold units for residential housing in Malaysia were surged significantly in four consecu-tive years starting from 2015 and Johor was ranked as the highest in unsold housing over other states in Malaysia. Therefore, this study aimed to identify the cause factors of unsold residential houing and to analyse the dynamic relationship between cause factors, unsold new housing, and housing market in Johor. The model was developed to clearly present the dynamic relationship between the factors and the unsold housing using a system dynamics approach, then the simula-tion results were compared with the real data, called behavioral validity test. After that, the model was validated through the Least Square method. Results showed three main factors that influenced unsold new housing stocks in Johor, namely house price, housing demand and hous-ing supply, meanwhile those three main factors were affected by other aspects, such as house-hold income, demand for housing loan, inflation rate and construction cost.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 010-003 - Analyse Air Pollution Index for Integer Value using Generalized Autoregressive Conditional **  
> Presented by: **_Asyikin Zamrus_**  
> Start Time: **_12:00 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The Air Pollution Index (API) of Malaysia has increased consistently in recent decades, becom-ing a serious environment issue concern. In this paper, we analyzed daily integer value time se-ries data for API in Penang and Sarawak from January to June in 2019 using generalized autoregressive conditional heteroskedasticity (GARCH) family for discrete case namely poisson integer value GARCH (INGARCH), negative binomial integer value GARCH (NBINGARCH) and integer value autoregressive conditional heteroskedasticity (INARCH) models. The pa-rameters of the models will be estimated using quasi likelihood estimator (QLE) and we compare their Akaike information criterion (AIC) to determine the best model fitted the data. The findings are very important for controlling the API results in future and taking protection meas-ure for conservation of the air.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 028-043 - Regional Frequency Analysis of Extreme Precipitation in Peninsular Malaysia**  
> Presented by: **_Iszuanie Syafidza Che Ilias_**  
> Start Time: **_12:15 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Peninsular Malaysia’s climate is directly affected by the weather from the mainland, which is be-ing hot and humid throughout the year, it is categorized as equatorial due to its location near to the equator. This study aims to improve the quality of estimation for the three hourly annual maximum daily precipitation of Peninsular Malaysia. Cluster analysis and regional frequency analysis based on L-moments were employed to investigate the areas represented by data ob-tained from 32 measuring stations and satellite based. The cluster analysis based on the “Ward’s method” classified Peninsular Malaysia into four regions. The identification of the best distribu-tion on L-Moment Ratio Diagram (LMRD) and goodness-of-fit criterion were performed to en-sure that all regions satisfy the heterogeneity measure. Five distribution functions were used in this study including Generalized Logistic (GLO), Generalized Extreme Value (GEV), General-ized Normal (GNO), Pearson Type 3 (PE3), and Generalized Pareto (GPA). The results show that, four distributions that are GNO, GLO, GEV, and GPA are found to be suitable candidates for the regional distribution. For the estimation of the quantiles, GNO, GEV, and GPA distribu-tions gave approximately similar quantile estimates until 50 years return period. Result suggest-ed that if the estimation of extreme precipitation at ungauged sites in which no flow data are available it would become a real problem for the scientists and hydrologists.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 097-087 - Free Convection Flow of Brinkman Type Fluid Through an Cosine Oscillating Plate**  
> Presented by: **_Ahmad Qushairi Mohamad_**  
> Start Time: **_12:30 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Heat transfer on an unsteady free convection flow of a Brinkman type fluid over an oscillating vertical plate has been studied. Appropriate dimensionless variables are used to reduce the dimensional governing equations along with imposed initial and boundary conditions into dimensionless forms. Using Laplace transform technique, the mathematical solutions for velocity and temperature are obtained. The graphical results are displayed to illustrate the influence of various embedded parameters such as Prandtl number, Grashof number, Brinkman type fluid parameter, phase angle and time upon velocity and temperature profiles.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  


### **ROOM 3 - MAHSURI ROOM**  

> #### **iCMS2021: 108-094 - Analysis Review on Challenges and Solutions to Computer Programming Teaching and Learning**  
> Presented by: **_Noor Hasnita Abdul Talib_**  
> Start Time: **_11:00 (MY time)_**  
> 
> Track - Computer Science & Information Technology   

<details>
<summary>**_Abstract_**</summary>  
<p>
**  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 096-079 - Information Security Culture: A Qualitative Approach on Management Support**  
> Presented by: **_Qamarul Nazrin Harun, Mohamad Mustaqim Junoh_**  
> Start Time: **_11:15 (MY time)_**  
> 
> Track - Computer Science   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Information security has been recognized as one of the important components that industry practitioners should address in the Industrial Revolution 4.0 (IR 4.0). In order to safeguard and protect organizational information from any dangers and threats, management requires to im-plement information security measures, both technical and non-technical. Information Security Culture (ISC) is a phrase used to describe a condition in which not only are individuals knowl-edgeable and skilled in terms of information security, but also processes and procedures, as well as technologies, are in place to protect and safeguard organization data. The outcomes of a study intended at identifying the ISC of Malaysian public organizations are presented in this paper. The study used a qualitative research methodology with an interview surveys as the data collec-tion technique. The results of the study propose 13 themes regarding management support in ISC. The findings emphasize the need of management support in strengthening the ISC in these participating organizations.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 062-050 - Geomagnetic Ap index and worldwide earthquake occurrences**  
> Presented by: **_Nur Anisah Binti Mohamed @ A Rahman_**  
> Start Time: **_11:30 (MY time)_**  
> 
> Track - Others   

<details>
<summary>**_Abstract_**</summary>  
<p>
*This work is to investigate the impact of geoeffective solar events and geomagnetic storms on the occurrences of earthquakes from 1994 to 2017 in a statistical perspective. In this study, the data for the geomagnetic Ap index and shallow worldwide earthquakes were used. The Ap index is obtained from the Helmholtz-Centre Postdam – GFZ German Research Centre for Geosciences, and the earthquake events are from the United States Geological Survey (USGS) earthquake catalogue. The superposed method and cluster analysis were used to identify the underlying structures of the data. From the analysis, we found that the average number of earthquakes gradually increasing from the onset of a geomagnetic storm and lasts for two days before it finally decreases. Cluster analysis clearly shows differences between the days before and after the geostorm (producing two major clusters). We introduced the Generalised Linear Mixed Models (GLMM) to investigate a dynamic relationship between high geomagnetic storms with earthquake frequency across time. The GLMM is suitable for correlated and nonlinearly distributed data. The characteristics of solar events related to the intense geomagnetic storm are presented in three different case studies to support the findings.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 084-073 - Unsteady MHD Casson fluid flow in a vertical cylinder with porosity and slip velocity effects**  
> Presented by: **_Wan Faezah Wan Azmi_**  
> Start Time: **_11:45 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The significance of Casson fluid flow in cylinder has recently attracted many researchers to study analytically, numerically and experimentally due to its unique behavior and related with the real-life applications such as blood flow in vessel tube. Due to the lack of consideration for slip boundary conditions, this paper investigated analytically the effects of slip velocity and magnetic on the pulsatile flow of Casson fluid past through a vertical cylinder in porous medi-um. The Casson fluid model was used under the influences of uniformly distributed magnetic field, oscillating pressure gradient and porous medium in order to obtain governing equations. The analytical solutions of velocities were then solved by Laplace and finite Hankel transforms. These fluid velocities were then presented graphically. The result shows that slip velocity influ-enced the behavior of Casson parameter and fluid velocity. Besides that, fluid velocity increases with the increases of Darcy number, while decreases when magnetic parameter increases. Thus, these findings are beneficial to explore further in the applications of biomedical engineering and pathology.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 088-070 - The Approximate Solution for A Triangular Fully Fuzzy Matrix Equation $\tilde{A}\ \tilde{X} \tilde{B} = \tilde{C}$**  
> Presented by: **_Wan Suhana Wan Daud_**  
> Start Time: **_12:00 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*A fully fuzzy matrix equation of $\tilde{A}\ \tilde{X} \tilde{B} = \tilde{C}$ has its own important in the application of control system engineering particularly in the situation of uncertainty. In this study, the equation is solved where the triangular fuzzy numbers be the variables of the equation. The algorithm that is used in the solution is consists of the conversion for the fully fuzzy matrix equation to a fully fuzzy linear system by utilizing the Kronecker and Vec-operator. Subsequently, the final solution is obtained by using the pseudoinverse method. A numerical example and the verification of the solution obtained are presented to demonstrate the contribution of this study.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 095-078 - Disjuctive Programming -Tabu Search Algorithm for Job Shop Scheduling Problem**  
> Presented by: **_Syarifah Zyurina Nordin_**  
> Start Time: **_12:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*In this paper, a tabu search has been selected to solve the job shop scheduling problem. Disjunc-tive programming (DP) with the shortest total processing time (STPT) and longest total pro-cessing time (LTPT) rules have been used to find the initial solution for tabu search. Further-more, the type of neighborhood structure used in tabu search is neighborhood structure 1 (N1). Comparison of results on different tabu list lengths and with benchmark values will be done to investigate the effect of the proposed disjunctive programming as an initial solution for tabu search. In conclusion, DP is managed to produce an overall good result in job shop scheduling.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 086-068 - Investment in Malaysia: Forecasting stock market using time series analysis**  
> Presented by: **_Fauhatuz Zahroh Shaik Abdullah_**  
> Start Time: **_12:30 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*This study aims to investigate the performance of the Kuala Lumpur Composite Index (KLCI) from 1997 to 2018. The ARIMA model approach was applied to study the KLCI time series. Model building and diagnostic checking techniques were conducted to determine a statistically adequate model. Subsequently, the next three years of the KLCI series is forecasted to estimate the return rate of investing in the Malaysian indexed stock market.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  
