---
title: "Parallel Sessions 4"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br></br>  

### **5th August, 2021**  
### **11:00 - 12:40 (MY time)**  

Select a room and session below to reveal more details and to access the button to join.  

***  

## {.tabset}  

### **ROOM 1 - MERBOK ROOM**  

> #### **iCMS2021: 017-009 - Mortality Modelling in Malaysia using O’Hare and Li in a State-Space Approach**  
> Presented by: **_Siti Rohani Mohd Nor_**  
> Start Time: **_11:00 (MY time)_**  
> 
> Track - Statistics  

<details>
<summary>**_Abstract_**</summary>  
<p>
*Accurate prediction on the life expectancy is crucial for the government, policy makers and health providers to make early retirement plan for ageing populations. The issue has grown in importance as many developments in stochastic mortality modelling have been introduced since 1992. Such approaches, however, are too complex since it requires two separate steps of estima-tion methods which would cause unreliable forecast on the life expectancy. Thus, this study aims to propose a new mortality model which incorporate the state-space into the modelling de-sign. The proposed model transformed the two-estimation methods of the traditional O’Hare and Li mortality method into a unified estimation in a state-space framework. The proposed mortali-ty model is applied to Malaysian mortality data for male and female from 1980 to 2020. The re-sults show that the proposed model provides better life expectancy prediction as compared to the other existing mortality models. Therefore, this study can be used as a reference to construct a new mortality table for making policy.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 037-029 - Performance Comparison of Spatial Outlier Detection Algorithms**  
> Presented by: **_Rossita M.Yunus_**  
> Start Time: **_11:15 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Several procedures outlined in the literature can only detect outliers in a non-spatial manner. Thus, the results obtained will have no protection against spatial outliers. The objective of this study is to select the best method for detecting spatial outliers.  Among the four methods, two of them use robust measures in the location and scale parameters, while the other two do not. Detection performance was assessed using simulated data as well as the PM10 concentration da-ta. The methods with robust measures have shown comparable results like the other two meth-ods when using the PM10 data and more accurate results in detecting spatial outliers in simulat-ed data.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 049-039 - Gaussian Integer Solutions of the Diophantine Equation $x^{4} + y^{4} = z^{3}$ for $xy$ **  
> Presented by: **_Shahrina Ismail_**  
> Start Time: **_11:30 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*This paper is concerned with the existence, types and cardinality of the solutions to the Diophantine equation $x^{4} + y^{4} = z^{3}$ in the Gaussian integers, for $x \ne y$. This paper aims to develop methods to be used in finding all Gaussian integer solutions to this equation. Results of the study show the existence of infinitely many solutions to this type of Diophantine equation in the ring of Gaussian integers for the case $x \ne y$. The main result obtained is a formulation of a generalized method to find all the solutions.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 091-075 - A Comparative Study of Moving Average Methods and ARIMA in Forecasting Gold Price**  
> Presented by: **_Hang See Pheng_**  
> Start Time: **_11:45 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The technical analysis is becoming an important reference to the traders in financial markets like stock markets, foreign exchange market, and gold market in recent years. Moving average is one of the most vastly used statistical tools in technical analysis to project and forecast the trend of data in financial markets. This study aims to compare the performance of the moving average methods and ARIMA in the gold market since gold is a precious commodity, globally accepted as a potential currency. In this study, three variations of moving averages including simple moving average (SMA), moving average convergence divergence (MACD), and autoregressive integrated moving average (ARIMA) are being implemented to forecast the daily gold price in the world. The dataset is collected from World Gold Council, which is a well-known website that provides reliable and updated information for gold price. The performance of the three moving average methods is compared by using the dataset from January 2020 until February 2021. The comparison between the moving average methods is done by using two different validation approaches. The SMA and MACD will be compared by considering the accuracy rate while performance of the SMA and ARIMA is validated by the forecasting error measurement – mean absolute percentage error (MAPE) and root mean square error (RMSE). The experimental results obtained indicating MACD perform better than SMA in term of accuracy rate. Further, SMA is found providing more smaller forecasting errors compare to ARIMA in gold price forecasting. The result favors to the SMA as compared to ARIMA due to the dataset obtained in the COVID-19 pandemic phase which observes the instability in the economy.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 106-090 - License Plate Number Recognition Using Support Vector Machine (SVM)**  
> Presented by: **_Hani Fathiah_**  
> Start Time: **_12:00 (MY time)_**  
> 
> Track - CMS   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Detecting license plates number from vehicle is a modern technology that being use for various purpose. In this study, license plate number recognition (LPNR) with support vector  machine (SVM) method is applied and use in manage control access to enter a secure parking lot. There are three (3) main processes in this study; data collection, algorithm development and license plate recognition. 26 data have been collected from the postgraduate students from Faculty of Computer and Mathematical Sciences (FSKM) in Universiti Teknologi MARA, Shah Alam. To develop the algorithm, it consists of seven (7) steps; license plate capture (image), pre-processing image, license plate localization, pre-recognition of character segmentation, character enhancement, character recognition and license plate number detection. The aim of this study is to develop the algorithm for LPNR and apply the developed algorithm using SVM. Based on the result, it is shown that 77% license plate number images have been successful being recognized using the developed algorithm using SVM.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 026-019 - B-Bistochastic-Volterra Quadratic Stochastic Operators on $S^{1}S^{1}$**  
> Presented by: **_Nur Natasha Binti Lim Boon Chye @ Mohd Hairie Lim_**  
> Start Time: **_12:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The main focus of this paper is to investigate the simplest non-linear Markov operators which is quadratic one. Study of quadratic stochastic operators (QSOs) is not an easy task as linear operator. There are several classes of QSOs were introduced such as Volterra QSOs, strictly non-Volterra QSOs, Orthogonal preserving QSOs, Centered QSOs and etc. However all the introduced classes were not yet cover the whole set of QSOs. The main problem in the nonlinear operator theory is to study the dynamics of nonlinear operators. This paper introduces a new class of QSOs, namely b-bistochastic-Volterra QSOs or simply bV-QSOs. In this paper, the canonical form of bVQSO defined on one dimensional simplex is provided. Next, the set of all fixed points of bV-QSOs are then obtained and classified into attracting, repelling, saddle and non-hyperbolic by applying Jacobian matrix. This helps understanding the dynamical behaviours of bV-QSOs.*  

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/v80aOqHxnEY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>
<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 032-021 - Evaluation of Predictors for the Development and Progression of Diabetic Retinopathy among Diabetes Patients**  
> Presented by: **_Syafawati Ab Saad_**  
> Start Time: **_12:30 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Diabetic retinopathy is one of the microvascular complications caused by prolonged uncontrolled diabetes. It is believed that diabetic retinopathy correlates with certain predictors and risk factors that might worsen the disease, eventually causing visual loss and blindness among diabetes patients. There are some predictors and risk factors that attribute to the development and progression of diabetic retinopathy, such as the duration of diabetes and HbA1c trends. This study aims to evaluate the predictors and risk factors associated with the development and/or progression of diabetic retinopathy. Retrospec-tive data were collected from a single healthcare facility in the northwest of Peninsular Malaysia. Patients included in this study were those with type 2 diabetes mellitus diag-nosed with diabetic retinopathy. The total number of patients involved in this study were 197, where 161 of them were newly diagnosed or with progressive diabetic reti-nopathy. The characteristics of diabetes patients with complication of diabetic retinopathy were described through descriptive statistics. Characteristics in-clude demographics data such as age, gender, race and clinical data such as HbA1c read-ings HbA1c, estimated glomerular filtration rate (eGFR), urea and haemoglobin concen-tration (Hb). The results show that few predictors and risk factors are significant to the development and progression of diabetic retinopathy among diabetes patients. By using multinomial logistic regression, this study offers better understanding of the significant predictors and risk factors related to diabetic retinopathy.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

***  

### **ROOM 2 - JERAI ROOM**  

> #### **iCMS2021: 101-082 - Fuzzy AHP and Its Application To Sustainable Energy Planning Decision Problem**  
> Presented by: **_Norliana Mohd Najib_**  
> Start Time: **_11:00 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The uncertainty during the decision-making process lead to difficulty in understanding the situa-tion of the problems occurs. However, there are lots of mathematical tools that described the multiplicity, complexity and sensitivity of the human thoughts in the decision process todays. To deal with uncertainties of information, the fuzzy set theory is introduced. Thus, the aim of the paper is to evaluate the alternatives selection with respect to sustainable energy planning problems using fuzzy multi criteria decision-making. In this paper, the fuzzy analytic hierarchy process is applied to conduct the relative weights priority of energy planning selection. The study suggests that CHP Power is recommended for the sustainable energy planning decision compared to other options of energy.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 066-0548 - Curvature Comparison of Bezier Curve, Ball Curve And Trigonometric Curve In Preserving The  Positivity Of Real Data**  
> Presented by: **_Afida Ahmad_**  
> Start Time: **_11:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The curvature of a curve is important in designing roads, construction of smooth surfaces, or grinding workpieces. Curvature is the tool to measure the smoothness of curves and surfaces. Therefore, in this paper, we have compared the curvature of three functions that are mostly used in curve design. These three functions are a rational cubic Bézier curve, a rational cubic Ball curve, and a cubic Trigonometric Bézier curve. Hence in this paper, the positivity of shape-preserving will be applied to real data. Conditions were imposed to preserve the positivity of the data and the results are presented.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 093-081 - Distance-Based Feature Selection for Low Level Data Fusion of Sensor Data**  
> Presented by: **_Maz Jamilah Masnan_**  
> Start Time: **_11:30 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Low level data fusion offers a mechanism for raw data from different sensor devices to be fused in an attempt to classify certain substance either in a form of liquid or gaseous. Commonly, this scenario creates a challenge for engineers to deal with large number of features over the number of observations, or also known as high dimensional problem. Traditionally, engineers prefer to apply feature extraction than feature selection in choosing important features for classification task. Thus, the objective of this article is to highlight a distance-based feature selection that can be used to replace the long-established feature extraction in multi sensor data fusion, specifically based on low level data fusion. Feature selection based on unbounded Mahalanobis distance $[0,\infty)$ is discussed in dealing with multi-group classification problem. Distances are filtered from largest to smallest values, and features with the larger distance value are considered im-portant. Feature selection analyses of several dataset have shown that the proposed distance pro-vides an effective and easy approach.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 065-053 - Modelling Malaysian Gold Prices**  
> Presented by: **_Isnewati Ab Malek_**  
> Start Time: **_11:45 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Nowadays, particularly after the unforeseen events of the pandemic triggered by covid-19, most people around the globe are beginning to grow an interest in gold because it offers a sustainable store of value. The Malaysian Kijang Emas is Malaysia’s official gold bullion coin and is minted by Malaysia’s Royal Mint. In comparison, the Kijang Emas has 999.9 millesimal fineness or 24 karats gold purity. The aim of this study is to describe the trend of Kijang Emas and to find the best-fitted model of the ARIMA model in modelling volatile data. The data is estimated using Box-Jenkins Methodology. The general finding of this study is that the Kijang Emas prices indicate the presence of an upward trend, and no seasonality component exists in the data series. In estimating the parameters for the Box-Jenkins ARIMA model, Maximum Likelihood Estima-tion (MLE) is used. The modelling performance of ARIMA is evaluated by using Akaike’s Information Criterion (AIC) and Schwartz Information Criterion (BIC). The results of the study concluded that ARIMA (2,1,1) is the best model by comparing the AIC and BIC value. The process of estimating the ARIMA model is done using Eviews software. In terms of forecasting performance, ARIMA (2,1,1) can be concluded as the best model for Kijang Emas prices data because it has the lowest value of AIC and BIC.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 018-010 - Numerical Solutions of Chaos Convection Model in a Horizontal Layer of Fluid Using Deep Learning Neural Networks (DNN)**  
> Presented by: **_Ruwaidiah Idris_**  
> Start Time: **_12:00 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Chaos convection plays an important role in the field of engineering such as designing electrical circuits, lasers and mechanical and magneto-mechanicaldevices, as well as understanding oscillatory chemical reactions and fluiddynamics. Due to high sensitivity to initial conditions, the nonlinear chaoticsystems such as fluid convection and turbulence occur up to tiny levels of external forcing, then the system becomes unstable. An uncontrolled system of convection will route the systems to unstable. When systems are unstable, it will damage the final product produced by industry such as microchips, crystal growth, welding of pipes line etc. In this paper, we developed analytical model for chaos convection in a horizontal layer of fluids derived using Galerkin truncated approximation techniques. The model obtained is then solved numerically using deep learning neural network (DNN). One of the advantages solving a nonlinear model using DNN is that we avoid the discretization process as found in the conventional numerical methods such as Newton and Runge-Kutta moethods. It is expected that DNN would help solving the model of chaos convection efficiently. *  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 103-084 - The Exact Wirelength of Fibonacci Cube Graphs on Complete Bipartite Graph**  
> Presented by: **_Siti Nur Aishah_**  
> Start Time: **_12:15 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Insert abstract here.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 105-089 - Radiation Effect on MHD Ferrofluid Flow with Ramped Wall Temperature and Arbitrary Wall Shear Stress**  
> Presented by: **_Nor Athirah Mohd Zin_**  
> Start Time: **_12:30 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

***  

### **ROOM 3 - MAHSURI ROOM**  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_11:00 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_11:15 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_11:30 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_11:45 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_12:00 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_12:15 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_12:30 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  
