---
title: "Parallel Sessions 5"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br></br>  

### **5th August, 2021**  
### **14:30 - 15:10 (MY time)**  

Select a room and session below to reveal more details and to access the button to join.  

***  

## {.tabset}  

### **ROOM 1 - MERBOK ROOM**  

> #### **iCMS2021: 073-060 - Impact of Suction on Rotating Flow of a Nanofluid past a Nonlinearly Shrinking Surface**  
> Presented by: **_Siti Nur Alwani Salleh_**  
> Start Time: **_14:30 (MY time)_**  
> 
> Track - Mathematics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*An investigation is considered to examine the rotating boundary layer flow and heat transfer past a nonlinear shrunk surface in a nanofluid by taking into consideration the influence of the suction effect at the surface. Three kinds of nanomaterials namely titanium dioxide, copper, and aluminum oxide are considered. The governing equations in the form of partial differential equations (PDEs) for momentum and energy are converted into a system of ordinary differential equations (ODEs). The shooting technique built in the MAPLE program is applied to the resulting system of equations. The impacts of the embedded parameters which include rotation, nanomaterial volume fraction, nonlinear and suction on the velocities, temperature, coefficient of skin friction and the heat transmission rate are plotted graphically and have been discussed further. The outputs showed that the presence of rotation in the flow rises the coefficient of the skin friction as well as the heat transmission rate. It is also detected that the nonlinear parameter accelerates the boundary layer separation in which the dual solution unites.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 071-058 - Detection of Differential Item Functioning for the Nine-Questions Depression Rating Scale for Thai North Dialect**  
> Presented by: **_Suttipong Kawilapat_**  
> Start Time: **_14:45 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*A different probability of responding to an item, differential item functioning (DIF),  could be occurred when individuals from different groups with the same ability and lead to misleading re-sults. This cross-sectional study to detect the DIF among 1,475 participants who participated in a validity study of the Nine-Questions Depression Rating Scale (9Q) for Thai North dialect. The 9Q was consisted of 9 polytomous items assessed for the severity (none, mild, moderate, and se-vere) and frequency (several days, more than a week, and nearly every day) of depression symp-toms according to DSM-5 within 2 weeks. The detection of DIF was considered between charac-teristics of participants including sex, age, underlying disease, and income using item response theory (IRT)-based and ordinal logistic regression (ORL)-based approach. The IRT difficulty pa-rameters for each item and threshold parameters for each possible category were estimated based on the generalized partial credit model. The results showed that depressed mood (item 1) has the highest discrimination parameter following by recurrent thoughts of death, suicidal ideation, or suicide attempts (item 9) (2.533 and 2.387, respectively). The IRT-based approach seemed to be proper than OLR-based approach in the examination of DIF and scoring due to the different of discrimination parameters. The DIF were presented between sex (item 5 and 8), age group (item 1, 2, 4, and 7), underlying disease (item 2, 3, 6, and 7). Scoring accounted for the discrimination and threshold parameters across the characteristics based on IRT approach might be useful to re-duce the bias of depression screening.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 012-004 - Application of the Length-Biased Weibull-Rayleigh Distribution to Fit the Rainy Season Rainfall for the Upper Ping River in Northern Thailand**  
> Presented by: **_Tanachot Chaito_**  
> Start Time: **_15:00 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Statistical distributions are important and useful in finding appropriate distributions for rainfall data and predicting the return levels of rainfall data. The objectives of this study are to apply the length-biased Weibull-Rayleigh (LBWR) distribution for fitting the rainy season rainfall data and to predict the return levels of the rainy season rainfall data. To do so, the LBWR distribution is compared with the Rayleigh, Weibull, and Weibull-Rayleigh distributions to find the best fit for the rainy season rainfall data from 1957 to 2020 of Samoeng (Chiang Mai) and Mae Tha (Lam-phun) stations in Thailand.  Judging from minimum values of the Kolmogorov-Smirnov test, Anderson-Darling test and Akaike information criteria, the results show that the LBWR distribu-tion is the best-fitting distribution of the rainy season rainfall data for both stations. Based on the prediction of the return levels of the rainy season rainfall data, the level of rainy season rain-fall at Samoeng station is higher than the return level at Mae Tha station. This could mean that Samoeng district may be at risk of flood compared with Mae Tha district. Therefore, the results from this study could be useful to formulate guidelines and strategies for flood prevention and water management in Samoeng district.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

***  

### **ROOM 2 - JERAI ROOM**  

> #### **iCMS2021: 061-047 - Harmony Search hyper-heuristic with different pitch adjustment operator for scheduling problems**  
> Presented by: **_Khairul Anwar_**  
> Start Time: **_14:30 (MY time)_**  
> 
> Track - Computer Science & Information Technology   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Harmony search algorithm (HSA) has been adapted into the hyper-heuristics’ framework as the high-level heuristic named as Harmony search-based Hyper heuristic (HSHH). Two operators in HSA are used to select and generate a heuristics vector. In this paper the pitch adjustment opera-tor will be used to enhance the basic HSHH. The purpose of applying pitch adjustment operator is to insert different way of heuristic selection instead of randomness in memory consideration operator. The effectiveness of the proposed method is tested with two different scheduling prob-lems. Experimentally, the new HSHH approach improve the basic HSHH and achieve compara-ble results with the comparative methods in the literature.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>

---  

> #### **iCMS2021: 059-045 - Exponential Model for simulation Data Via Multiple Imputations in the present of Partly Interval Censored Data**  
> Presented by: **_Faiz Ahmed Mohamed Elfaki_**  
> Start Time: **_14:45 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Survival analysis or time-to-event analysis refers to a set of methods to analyze the time between entry to a study and a subsequent event where time to failure of an experimental unit and that could be censored as right, left, interval, or Partly Interval Censored (PIC). In this paper, the likelihoods are applied in the exponential model in order to estimate the parameters and function of survival when multiple imputation method is used for partly interval-censored data. The numerical evidence via simulated breast cancer data suggests that the estimates from multiple imputation are more accurate*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
</p>
</details>  

---  

> #### **iCMS2021: 059-061 - Accelerated Failure Time (AFT) model for Simulation Partly Interval Censored Data**  
> Presented by: **_Faiz Ahmed Mohamed Elfaki_**  
> Start Time: **_15:00 (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*The performance of maximum likelihood estimators of the parameters of Accelerated Failure Time (AFT) regression model based on Weibull distribution with simple imputations methods under Partly-Interval Censored (PIC) data is studied. The proposed model is tested through the simulation data and the result were compare with semiparametric model. The result indicate that the AFT with Weibull distribution is comparable with Cox model under simulated PIC data via breast cancer data in the present of imputation techniques. In additional to that the result suggested that the parameters of the our model are stable and the treatments are significant for simulated breast cancer patients.*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
<!-- </p> -->
</details>  

---

> ### **iCMS2021: 003-001 - A review on individual loss reserving for non-life insurance** {-}  
> Presented by: **_Ang Siew Ling_**  
> Start Time: **_15:15  (MY time)_**  
> 
> Track - Statistics   

<details>
<summary>**_Abstract_**</summary>  
<p>
*In recent decades, there has been great success with deterministic and stochastic unpaid claim reserving models based on triangles, such as those related to the chain-ladder model. However, with the increased need for more accurate reserving models, taking advantage of the information embedded in individual claims data with appropriate claims development models are a promising alternative compared with the traditional aggregate loss development triangles. This research reviews on the development of using the individual claims data for reserving estimation.*  
</p>
</details>  

***  

### **ROOM 3 - MAHSURI ROOM**  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_14:30 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
<!-- </p> -->
<!-- </details> -->

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_14:45 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
<!-- </p> -->
<!-- </details>   -->

---  

> #### **Paper ID - Title**  
> Presented by: **_Speaker Name_**  
> Start Time: **_15:00 (MY time)_**  
> 
> Track   

<details>
<summary>**_Abstract_**</summary>  
<p>
*Place or insert abstract here*  

<!-- [**Speaker Name, Country**]()   -->

<!-- [[Join]]()   -->
<!-- </p> -->
<!-- </details>   -->
