---
title: "Conference programme"
output:
  html_document: 
    includes:
        in_header: assets/header.html
        after_body: footer.html
    #toc: false
    #toc_float: false
---

<link rel="stylesheet" href="styles.css" type="text/css">

<br>

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/eP-TGhCGLpo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>

<br>  

Use the buttons below to access a talk at the designated time. Where more than one session is available, click 'see options' to view your choices. For further help and guidance please see the [help section](help.html).  

<!-- **NOTE:** The [[JOIN]]() button can only be accessed by registered participants.   -->

## {.tabset}  

### Day 1 - August 4, 2021  

> 08:00 - 08:40 (MALAYSIA time)  
>  
> ### Registration  
> Familiarise yourself with the conference platform and check that your equipment is working by accessing the 'registration' session.  
>  
<!-- > [[JOIN]]()   -->

---  

> 08:40 - 08:45 (MY time)  
>  
> ### Doa Recitation and National Anthem  
>  

---

> 08:45 - 09:00 (MY time)  
>  
> ### Welcoming Speech by:  
>  
> **PROF. DR. MOHAMAD ABDULLAH HEMDI**  
> Rector, Universiti Teknologi Mara (UiTM) Kedah  
>  

--- 

> 09:00 - 09:15 (MY time)  
>  
> ### Officiating Speech by:  
>  
> **PROF Ts DR. HARYANI HARON**  
> Dean, Faculty of Computer & Mathematical Sciences,  
> Universiti Teknologi MARA (UiTM) Shah Alam  
>  


---  

> 09:15 - 09:20 (MY time)  
>   
> ### Video Montage  
>  

<!-- <video width="320" height="240" controls> -->
<!--   <source src="./videos/EnglishVersion1.mp4" type="video/mp4"> -->
<!--   Your browser does not support the video tag. -->
<!-- </video> -->

<!-- <center> -->
<!-- ```{r echo=FALSE} -->
<!-- library(embedr) -->

<!-- # embed .mp4 video -->
<!-- video <- "./videos/EnglishVersion1.mp4" -->
<!-- embed_video(video, type = "mp4", width="560", height="315", attribute = "control") -->

<!-- ``` -->
<!-- </center> -->


---  

> 09:20 - 10:20 (MY time)  
>  
> ### Keynote Speaker 1  
> 
> **PROF. DR. YAP BEE WAH**  
> Universiti Teknologi MARA (UiTM) Shah Alam  
>  
> **_RESEARCH AND INNOVATION: OPPORTUNITIES AND CHALLENGES FOR ACADEMIA_**  
>  


---  

> 10:20 - 11:00 (MY time)  
>  
> ### Invited Speaker 1  
>  
> **MR. MUHAMMAD HAZLAN BIN HAMDAN**  
> Head of Data Analytics, MISC  
>  
> **_THE OPERATIONS AND THE MONEY-MAKING DATA SCIENTIST_**  
> THE KIND YOU SHOULD HIRE   
>

---  

> 11:00 - 12:40 (MY time)  
>  
> ### Parallel Session 1  
> Choose room and sessions to attend.  
>  
> [[SEE OPTIONS]](break1.html)  
  
---  

> 12:40 - 14:30 (MY time)  
>  
> ### Refreshment Break  
>  

---  

> 14:30 – 15:30 (MY time)  
>  
> Keynote Speaker 2  
>  
> **DR. MATTHIAS TEMPL**  
> Institute of Data Analysis and Process Design  
> Zurich University of Applied Sciences, Switzerland  
>  
> **_ANALYSIS AND IMPUTATION OF MISSING VALUES_**  
> 
<!-- > <h3> -->
<!-- > <ul class="pager"> <!--this is the style of the button--> -->
<!-- > <li><a href="keynote2.html">**VIEW SPEAKER BIO**</a></li> <!--This button takes me to the table of contents--> -->
<!-- > <li><a href="https://meet.google.com/rmi-nqun-bfy">**JOIN**</a></li> <!--This button takes me to the previous page--> -->
<!-- > </ul> -->
<!-- > </h3>   -->

---  

> 15:30 – 16:10 (MY time)  
>  
> Invited Speaker II  
> 
> **ASSOC. PROF. ANTONIADE-CIPRIAN ALEXANDRU-CARAGEA PhD**  
> Vice Rector  
> Scientific Research and International Relations  
> Ecological University of Bucharest  
>  
> **_SMARTCITY DEVELOPMENT AND IMPLEMENTATION IN ROMANIA_**  
>  


---  

> 16:10 - 16:50 (MY time)  
>  
> ### Parallel Session 2  
> Choose room and sessions to attend.  
>  
> [[SEE OPTIONS]](break2.html)  

<a href="#top">Back to top</a>  

***  

### Day 2 - August 5, 2021  

> 08:00 - 08:40 (MALAYSIA time)  
>  
> ### Registration  
> Familiarise yourself with the conference platform and check that your equipment is working by accessing the 'registration' session.  
>  
<!-- > [[JOIN]]()   -->

---  

> 08:40 - 10:15 (MY time)  
>  
> ### Parallel Session 3  
> Choose room and sessions to attend.  
>  
> [[SEE OPTIONS]](break3.html)  
  
---  

> 10:15 – 111:00 (MY time)  
>  
> Invited Speaker III  
> 
> **Dr. Gerald Cheang**  
> Senior Lecturer  
> UNISA  
> South Australia  
>  
> **_A HISTORY OF EXCHANGE OPTION PRICING MODELS_**  
>  


---  

> 11:00 - 12:40 (MY time)  
>  
> ### Parallel Session 4  
> Choose room and sessions to attend.  
>  
> [[SEE OPTIONS]](break4.html)  
  
---  

> 12:40 - 14:30 (MY time)  
>  
> ### Refreshment Break  
>  

---  

> 14:30 - 15:10 (MY time)  
>  
> ### Parallel Session 5  
> Choose room and sessions to attend.  
>  
> [[SEE OPTIONS]](break5.html)  
  
---  

> 15:10 - 15:25 (MY time)  
>  
> ### Refreshment Break  
>  

---  

> 15:25 - 16:00 (MY time)  
>  
> ### Closing Speech by:  
>  
> **PROF. DR. MOHAMAD ABDULLAH HEMDI**  
> Rector, Universiti Teknologi Mara (UiTM) Kedah  
>  
> **_Announcement of BEST PAPER AWARD_**  
>
<!-- > [[JOIN]]()   -->

---  

> 16:00 (MY time)
>  
> Program Ends


