---
title: "Plenaries"
---

<link rel="stylesheet" href="styles.css" type="text/css">

---  

> August 4, 2021 at 09:20 - 10:20 (MY time)
>  
> Keynote 1 - Research and Innovation: Opportunities and Challenges for Academia  
> Presented by: Prof. Dr. Yap Bee Wah  

<details>
<summary>read more ...</summary>  
<p>
Words of wisdoms...  

Synopsis ...  

[[VIEW BIO]](keynote1.html)  
</p>

<center>
<!-- <object data="./assets/pdf/speakers/Yap.pdf" type="application/pdf" width="100%" height="660px"> -->
<!--   <embed src = "./assets/pdf/speakers/Yap.pdf" /> -->
<!--   <p>Alternative text - include a link <a href="./assets/pdf/CheangiCMS2021FinalVersion.pdf">to the PDF!</a></p> -->
<!-- </object> -->

<embed src="./assets/pdf/speakers/Yap.pdf" type="application/pdf" width="100%" height="660px" />
<p>If you can't view the pdf file, click on the file's link - <a href="./assets/pdf/speakers/Yap.pdf"> Download PDF!</a></p>
</center>

</details>

***  

> August 4, 2021 at 10:20 - 11:00 (MY time)
>  
> Invited Speaker 1 - THE OPERATIONS AND THE MONEY-MAKING DATA SCIENTIST  
> Presented by: Mr. Muhammad Hazlan Hamdan  

<details>
<summary>read more ...</summary>  
<p>
Words of wisdoms...  

Synopsis ...  

[[VIEW BIO]](invited2.html)  
</p>
</details>  

***  

> August 4, 2021 at 14:30 - 15:30 (MY time)
>  
> Keynote 2 - Analysis and Imputation of Missing Values  
> Presented by: Dr. Matthias Templ  

<details>
<summary>read more ...</summary>  
<p>
<blockquote style="font-size:larger;">
  <span style="color:green;">“I did then what I knew how to do. Now that I know better, I do better.”</span><cite> ― Maya Angelou</cite></blockquote>
\
<span style="color:red;">**_Synopsis_**</span>\

Data from almost all sciences may contain missing values, and the reasons for their appearance are manifold. Missing values occur when measurements fail, from non-response in surveys, when analysis results are lost, or when measurements are implausible.\
\
Missing values can have a strong influence on resulting figures and analysis which could be biased and their variance may be underestimated if missing values and their structure - best analyzed with appropriate visualization tools - are ignored.\
\
Planning to analyze data that include missing values involves answering the following questions:\
\
<span style="color:yellow;">
  - Which kind of missing data are present in the data?  
  - What mechanism does this missing data follow?  
  - Which imputation strategy is appropriate for these data?  
  - What are the consequences of a sensitivity analysis?  
  - Is the aim to train and use a predictive model with high predictional power?  
</span>
\
Topics like the visualization of missing values and imputed values can answer some of these questions. This allows to observe the data structure and the mechanism of the missing values and gives many insights into the data set.\ 
\
In addition, outliers should be considered and robust methods for imputation used that bound the influence of outliers. In addition, we extensively discuss the imputation of data sets with mixed scaled variables. a data set may contain a mix of continuous, semi-continuous, binary, nominal, ordinal, count, or compositional variables.\ 
\
This talk gives a broad overview of methods for missing values and imputation of missing values, but also shows some new developments in the mentioned topics.\

[[VIEW BIO]](keynote2.html)  
</p>

<center>
<embed src="./assets/pdf/speakers/Matthias.pdf" type="application/pdf" width="100%" height="660px" />
<p>If you can't view the pdf file, click on the file's link - <a href="./assets/pdf/speakers/Matthias.pdf"> Download PDF!</a></p>
</center>  

</details>  

***  

> August 4, 2021 at 15:30 - 16:10 (MY time)
>  
> Invited Speaker 2 - Smartcity Development and Implementation in Romania  
> Presented by: Assoc. Prof. Antoniade-Ciprian ALEXANDRU-CARAGEA PhD  

<details>
<summary>read more ...</summary>  
<p>
Words of wisdoms...  

Synopsis ...  

[[VIEW BIO]](invited1.html)  
</p>

<center>
<embed src="./assets/pdf/speakers/cip.pdf" type="application/pdf" width="100%" height="660px" />
<p>If you can't view the pdf file, click on the file's link - <a href="./assets/pdf/speakers/cip.pdf"> Download PDF!</a></p>
</center>  

</details>  

***  

> August 5, 2021 at 10:15 - 11:00 (MY time)
>  
> Invited Speaker 3 - A History of Exchange Option Pricing Models  
> Presented by: Dr. Geral Cheang  

<!-- <div> align="center" style="background-color:black; widdt:100%; height=660px"> -->
<!-- <embed src= "CheangiCMS2021FinalVersion.pdf" type="application/pdf" style="width:90%; height:100%> -->
<!-- <div> -->

<details>
<summary>read more ...</summary>  
<p>
<blockquote style="font-size:larger;">
  <span style="color:green;">“Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.”</span><cite> ― Franklin D. Roosevelt</cite></blockquote>
\
<span style="color:red;">**_Synopsis_**</span>\

I will first start off with describing what options on underlying assets are. Then I will outline the history of modern option pricing theory (on a single asset/stock) including the Black-Scholes-Merton (1973) stock pricing/option pricing model. The talk will then move on to exchange options which allow the holder to exchange one unit of one asset with one unit of another different type of asset upon exercise. The first exchange option pricing model was formulated by Margrabe (1978) based on the Geometric Brownian Motion stock pricing model of Black-Scholes-Merton. However, the Black-Scholes-Merton model is known to be inadequate in addressing jumps and stochastic volatility observed in stock prices, hence extensions to the model are need to price options based on single assets as well as on multiple assets such as exchange options. I will then talk about my work in extending the basic Margrabe exchange option model to models that allow for jumps in the asset prices (Cheang and Chiarella, 2011; Cheang and Lian, 2015) and also for both jumps and stochastic volatility (Cheang and Garces, 2020; Garces and Cheang, 2021).\

[[VIEW BIO]](invited3.html)  
</p>

<center>
<embed src="./assets/pdf/speakers/Cheang.pdf" type="application/pdf" width="100%" height="660px" />
<p>If you can't view the pdf file, click on the file's link - <a href="./assets/pdf/speakers/Cheang.pdf"> Download PDF!</a></p>
</center>  

</details>  

